doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8mb4
                default_table_options:
                    collate: utf8mb4_general_ci
            movies:
                url: '%env(resolve:DATABASE_MOVIES_URL)%'
                charset: utf8mb4
                default_table_options:
                    collate: utf8mb4_general_ci
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
            movies:
                connection: movies
                mappings:
                    AppMovies:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Movies/Entity'
                        prefix: 'App\Movies\Entity'
                        alias: AppMovies
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
